language: node_js

node_js:
  - '10'

branchs:
  only:
    - master

script:
  - yarn build

before_install:
  - openssl aes-256-cbc -K $encrypted_a339192dcd1f_key -iv $encrypted_a339192dcd1f_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa

addons:
  ssh_known_hosts:
    - wwww.aqcoder.com

after_success:
  - ssh root@www.aqcoder.com -o StrictHostKeyChecking=no "rm -rf /var/www/gvf-client/.nuxt"
  - travis_wait 30 scp -r .nuxt root@www.aqcoder.com:/var/www/gvf-client/
  - ssh root@www.aqcoder.com -o StrictHostKeyChecking=no "pm2 restart gvf-client"
