language: node_js

node_js:
  - '10'

branchs:
  only:
    - master

script:
  - yarn build

before_install:
  - openssl aes-256-cbc -K $encrypted_a339192dcd1f_key -iv $encrypted_a339192dcd1f_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa

addons:
  ssh_known_hosts:
    - www.aqcoder.com:29371

after_success:
  - ssh -p 29371 root@www.aqcoder.com "rm -rf /var/gvf-client/.nuxt"
  - scp -P29371 -r .nuxt root@www.aqcoder.com:/var/gvf-client/
  - ssh -p 29371 root@www.aqcoder.com "pm2 restart gvf-client"
