language: node_js

node_js:
  - '10'

branchs:
  only:
    - master

script:
  - yarn build

before_install:
  - openssl aes-256-cbc -K $encrypted_a339192dcd1f_key -iv $encrypted_a339192dcd1f_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa

addons:
  ssh_known_hosts:
    - 122.51.246.153

after_success:
  - ssh root@122.51.246.153 -o StrictHostKeyChecking=no "rm -rf /var/www/gvf-client/.nuxt"
  - scp -r .nuxt root@122.51.246.153:/var/www/gvf-client/
  - ssh root@122.51.246.153 -o StrictHostKeyChecking=no "pm2 restart gvf-client"
