language: node_js
node_js:
  - '10'
script:
  - yarn build
before_install:
  - openssl aes-256-cbc -K $encrypted_a339192dcd1f_key -iv $encrypted_a339192dcd1f_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d

after_success:
  - scp -P$sshport dist/* www.aqcoder.com:/var/www/gvf-client/
addons:
  ssh_known_hosts:
    - www.aqcoder.com
