language: node_js

node_js:
  - '10'

branchs:
  only:
    - master

script:
  - yarn build

before_install:
  - openssl aes-256-cbc -K $encrypted_a339192dcd1f_key -iv $encrypted_a339192dcd1f_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa

addons:
  ssh_known_hosts:
    - 198.181.45.145:29371

after_success:
  - ssh -p $ssh_port ${ssh_user}@$ssh_host "rm -rf /var/gvf-client/.nuxt"
  - scp -P$ssh_port -r .nuxt ${ssh_user}@${ssh_host}:/var/gvf-client/
  - ssh -p $ssh_port ${ssh_user}@$ssh_host "pm2 restart gvf-client"
